environment:
  - "FORCE_COLOR=1"
processes:

  bun-install:
    command: bun install --color=always

  mill-build:
    # initial mill build, so that vite finds the js files referenced in main.js
    command: mill --color true frontend.fastLinkJS

  vite-dev:
    command: bunx vite dev --port 5173 --strictPort
    ports:
      - 5173:5173
    depends_on:
      bun-install:
        condition: process_completed_successfully
      mill-build:
        # vite should start, even if the initial build failed
        condition: process_completed

  mill-watch:
    command: mill --color true --watch "{backend.runBackground,frontend.fastLinkJS}"
    env:
      LOG_LEVEL:debug
    depends_on:
      mill-build:
        # watch should start, even if the initial build failed
        condition: process_completed

  db-seed:
    command: echo schema.sql | entr -n bash -c "echo seeding database...; rm -f data.db; sqlite3 -init /dev/null data.db < schema.sql && echo success."

  # auth:
  #   command: |
  #     docker run -p 3000:3000 -p 3001:3001 \
  #       -v authn-data:/data \
  #       -e APP_DOMAINS="localhost" \
  #       -e AUTHN_URL="http://localhost:3000" \
  #       -e PORT=3001 \
  #       -e PUBLIC_PORT=3000 \
  #       -e SECRET_KEY_BASE="test" \
  #       -e DATABASE_URL="sqlite3://localhost//data/authn.db" \
  #       -e ENABLE_SIGNUP=false \
  #       -e HTTP_AUTH_USERNAME="admin" \
  #       -e HTTP_AUTH_PASSWORD="adminpw" \
  #       keratin/authn-server:latest \
  #       sh -c "./authn migrate && ./authn server"
  #
